<!-- pointcheckout Logo -->
<img src="https://www.pointcheckout.com/image/logo.png"
     alt="<?php echo Mage::helper('pointcheckout')->__('Point Checkout') ?>" class="v-middle" style="height:25px;"
     id="pointcheckout-logo"/>
<span style="margin-top: 6px;">
    &nbsp;
    <small>
        <a href="https://www.pointcheckout.com/info/what-is-pointcheckout" onclick="javascript:window.open('https://www.pointcheckout.com/info/what-is-pointcheckout','olcwhatispointcheckout','toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=yes,left=100,top=50,width=500, height=400'); return false;">
   What is PointCheckout?</a>
    </small>
</span>
