<!-- pointcheckout Logo -->
<img src="<?php echo $this->getSkinUrl('images/pointcheckout/logo.png', array('_secure' => Mage::app()->getRequest()->isSecure())); ?>"
     alt="<?php echo Mage::helper('pointcheckout')->__('Point checkout') ?>" class="v-middle" style="height:35px;"
     id="pointcheckout-logo"/>
<span style="margin-top: 6px;">
    &nbsp;
    <small>
        <a href="<?php echo "#"; ?>" target="_blank">
            <?php echo Mage::helper('pointcheckout')->__('What is this ?'); ?>
        </a>
    </small>
</span>
