<!-- pointcheckout Logo -->
<img src="http://www.pointcheckout.com/image/logo.png"
     alt="<?php echo Mage::helper('pointcheckout')->__('Point checkout') ?>" class="v-middle" style="height:35px;"
     id="pointcheckout-logo"/>
<span style="margin-top: 6px;">
    &nbsp;
    <small>
        <a href="<?php echo "https://www.pointcheckout.com"; ?>" target="_blank">
            <?php echo Mage::helper('pointcheckout')->__('visit pointcheckout.com'); ?>
        </a>
    </small>
</span>
